### ISSUE TITLE
Custom color for the pomm timeline

### ISSUE THREAD

**Issue by sanpii** [pomm-project/pomm-symfony-bridge#12]
https://github.com/symfony/symfony/issues/7882

**Comment by stood** [comment]
you  want the color is a parameter ? And what color by default do you want ?

**Comment by sanpii** [comment]
> you want the color is a parameter ?

No.

> And what color by default do you want ?

A pink like other database tools: #c2d

**Comment by stood** [comment]
@sanpii I think, it's ok for the moment.

**Comment by stood** [comment]
close ?
