### ISSUE TITLE
With Symfony 3, the profiler does not seem to work

### ISSUE THREAD

**Issue by pounard** [pomm-project/pomm-symfony-bridge#20]
There are no errors, but the query count is always 0 and the report always empty. I will inspect this.

**Comment by stood** [comment]
@pounard : https://github.com/pomm-project/pomm-bundle/pull/50 correct your bug?

**Comment by chanmix51** [comment]
May we close this issue ?

**Comment by mvrhov** [comment]
IMO yes. At least for me the latest master works in 3.1

**Comment by pounard** [comment]
Sorry, I had a lot of work and completly fogotten this issue, I trust other testers so it should probably be closed :)
