### ISSUE TITLE
Bridge requires Twig extension

### ISSUE THREAD

**Issue by chanmix51** [pomm-project/pomm-symfony-bridge#25]
When building an API, there is no need for Twig. It may be needed in the dev environment because of the profiler but in production, even though the profiler extension is not loaded, Pomm still requires the twig service to be present & configured.

When no twig configuration is set, Symfony throws the following exception

```
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: 
The service "pomm.twig_extension" has a dependency on a non-existent service "twig.loader".
```

**Comment by mvrhov** [comment]
Check my PR to bundle. I've fixed this exact issue there.

**Comment by sanpii** [comment]
PR merged. Is it fixed?

**Comment by mvrhov** [comment]
@chanmix51 should know if he was using it anywhere else. I've fixed the issue in a bundle.
