### ISSUE TITLE
Explain queries with non-string parameter

### ISSUE THREAD

**Issue by sanpii** [pomm-project/pomm-symfony-bridge#3]
$this->pomm['default']
                ->getModel('AppBundle\\Model\\Db\\PublicSchema\\TeleinfoModel')
                ->findWhere('created = $*', [new \DateTime('2014-02-17 22:05:06.566862')]);

Explain this query throw an error:

    Catchable Fatal Error: Object of class DateTime could not be converted to string in vendor/pomm-project/foundation/sources/lib/Session/Connection.php line 401

**Comment by chanmix51** [comment]
This is a [Foundation bug](https://github.com/pomm-project/Foundation/issues/8)

I close this one.
